alias l='ls -lhA'
alias ll='ls -lha'
alias lsd='ls -l|grep "^d"'
alias lt='ls -lhAt'
alias e='exit'
alias psme='ps -fu$LOGNAME'
alias psload='ps -eo state,user,command|grep ^[RD]'
alias dotpath='PATH=.:$PATH'
alias addpath='PATH=$PWD:$PATH'
alias totalsize='du -sxh'
